{
 "title": "Greetify Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Container Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"greetify-backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Greeting clicks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, sum by (id, language, greeting) (greetings_clicked_count{app=\"greetify\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Greetify backend CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"greetify-backend\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3 HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(3, sum by(path, method) (http_requests_total{job=\"greetify-backend\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Greetify backend memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"greetify-backend\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Created greetings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(greetings_created_count{container=\"greetify-backend\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}